version: '3.4'
services:
  pedelogo.catalogo.api:
    image: kubedevio/pedelogo-catalogo:v1.0.0
    ports: 
      - 8080:80
    environment:
      Mongo_Host: mongodb
      Mongo_User: mongouser
      Mongo_Password: mongopwd
      Mongo_Port: 27017
      Mongo_DataBase: admin
    depends_on:
      - mongodb
    networks:
      - pedelogo_network
  mongodb:
    image: mongo:4.2.8
    networks:
      - pedelogo_network
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongopwd
  prometheus:
    image: prom/prometheus:v2.22.0
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
    depends_on:
      - pedelogo.catalogo.api
    networks:
      - pedelogo_network  
networks:
  pedelogo_network:
    driver: bridge      
